eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
spring:
  application:
    name: eureka-service
server:
  port: ${PORT_EUREKA_SERVER:8761}
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
info:
  author: Marcelo Massayuki Nader
  mail: marcelo.m.nader@gmail.com
  severity: Medio